blog/urls.py
from django.urls import path
from .views import PostList, post_detail

urlpatterns = [
    path('',
         PostList.as_view(template_name='blog/post_list.html'),
         name='blog_post_list'),

    path('post/<int:year>/<int:month>/<str:slug>',
         post_detail,
         name='blog_post_detail'),
]

organizer/urls.py
from django.urls import path
from .views import tag_list, tag_detail, startup_list, startup_detail, TagCreate


urlpatterns = [
    path('tag/', tag_list, name='organizer_tag_list'),
    path('tag/create', TagCreate.as_view(),


         name='organizer_tag_create'),
    path('tag/<str:slug>', tag_detail, name='organizer_tag_detail'),
    path('', startup_list, name='organizer_startup_list'),
    path('startup/<str:slug>', startup_detail, name='organizer_startup_detail'),
]

startup/urls.py
from django.contrib import admin
from django.urls import path, include
from organizer import urls as organizer_urls
from blog import urls as blog_urls
from .views import redirect_root


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(organizer_urls)),
    path('blog/', include(blog_urls)),
    # path('', redirect_root),
]

blog/models.py
from django.db import models
from organizer.models import Startup, Tag
from django.urls import reverse

# Create your models here.


class Post(models.Model):
    title = models.CharField(max_length=63)
    slug = models.SlugField(max_length=63, unique_for_month='pub_date', help_text='A label for URL config.')
    text = models.TextField()
    pub_date = models.DateField(verbose_name='date published', auto_now_add=True)
    tags = models.ManyToManyField(Tag, related_name='blog_posts')
    startups = models.ManyToManyField(Startup, related_name='blog_posts')

    def get_absolute_url(self):
        return reverse('blog_post_detail',
                       kwargs={'slug': self.slug,
                               'year': self.pub_date.year,
                               'month': self.pub_date.month})

    def __str__(self):
        return f"{self.title} on {self.pub_date.strftime('%Y-%m-%d')}"

    class Meta:
        verbose_name = 'blog post'

organizer/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class Tag(models.Model):
    name = models.CharField(max_length=31, unique=True)
    slug = models.SlugField(max_length=31, unique=True, help_text='A label for URL config.')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('organizer_tag_detail', kwargs={'slug': self.slug})

    class Meta:
        """
        Order the Tag model alphabetically by the name field.
        """
        ordering = ['name']


class Startup(models.Model):
    name = models.CharField(max_length=31, db_index=True)
    slug = models.SlugField(max_length=31, unique=True, help_text='A label for URL config.')
    description = models.TextField()
    founded_date = models.DateField(verbose_name='data founded')
    contact = models.EmailField()
    website = models.URLField(max_length=255)
    tags = models.ManyToManyField(Tag)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('organizer_startup_detail',
                       kwargs={'slug': self.slug})

    class Meta:
        """
        Order the lists of Startup objects by name and the latest object should be with the most recent
        founded_date field.
        """
        ordering = ['name']
        get_latest_by = 'founded_date'


class NewsLink(models.Model):
    title = models.CharField(max_length=63)
    pub_date = models.DateField(verbose_name='date published')
    link = models.URLField(max_length=255)
    startup = models.ForeignKey(Startup, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.startup}: {self.title}"

    class Meta:
        verbose_name = 'news article'
        ordering = ['-pub_date']
        get_latest_by = 'pub_date'

blog/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'

    def clean_slug(self):
        return self.cleaned_data['slug'].lower()

organizer/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import Tag, NewsLink, Startup


class SlugCleanMixin:
    def clean_slug(self):
        new_slug = self.cleaned_data['slug'].lower()
        if new_slug == 'create':
            raise ValidationError('Slug may not be "create".')
        return new_slug


class TagForm(SlugCleanMixin, forms.ModelForm):

    class Meta:
        model = Tag
        fields = '__all__'

    def clean_name(self):
        return self.cleaned_data['name'].lower()


class NewsLinkForm(forms.ModelForm):
    class Meta:
        model = NewsLink
        fields = '__all__'


class StartupForm(SlugCleanMixin, forms.ModelForm):
    class Meta:
        model = Startup
        fields = '__all__'

blog/views.py
from django.shortcuts import get_object_or_404, render
from django.views.generic import View
# Create your views here.

from .models import Post


def post_list(request):
    return render(request,
                  'blog/post_list.html',
                  {'post_list': Post.objects.all()})


def post_detail(request, year, month, slug):
    post = get_object_or_404(Post,
                             pub_date__year=year,
                             pub_date__month=month,
                             slug=slug)
    return render(request,
                  'blog/post_detail.html',
                  {'post': post})


class PostList(View):
    """
    Class based view.
    """
    template_name = ''

    def get(self, request):
        return render(request,
                      self.template_name,
                      {'post_list': Post.objects.all()})

organizer/views.py
from django.shortcuts import get_object_or_404, render,redirect
from .models import Tag, Startup
from .forms import TagForm
from django.views.generic import View

# Create your views here.

def tag_create(request):
    if request.method == 'POST':
        form = TagForm(request.POST)
        if form.is_valid():
            new_tag = form.save()
            return redirect(new_tag)
        else:
            return render(
                request,
                'organizer/tag_form.html',
                {'form': form}
            )
    else:
        form=TagForm()
        return render(
            request,
            'organizer/tag_form.html',
            {'form': form}
        )


class TagCreate(View):
    form_class = TagForm
    template_name = 'organizer/tag_form.html'

    def get(self, request):
        return render(request,
                      self.template_name,
                      {'form': self.form_class()})

    def post(self, request):
        bound_form = self.form_class(request.POST)
        if bound_form.is_valid():
            new_tag = bound_form.save()
            return redirect(new_tag)

        else:
            return render(request,
                          self.template_name,
                          {'form': bound_form})



def tag_list(request):
    tag_list = Tag.objects.all()
    return render(request,
                  'organizer/tag_list.html',
                  {'tag_list':tag_list}
                  )


def tag_detail(request, slug):
    tag = get_object_or_404(Tag, slug__iexact=slug)
    # template = loader.get_template('organizer/tag_detail.html')
    # context = {'tag': tag}
    # output = template.render(context)
    # return HttpResponse(output)
    return render(request,
                  'organizer/tag_detail.html',
                  {'tag': tag})


def startup_list(request):
    return render(request,
                  'organizer/startup_list.html',
                  {'startup_list': Startup.objects.all()})


def startup_detail(request, slug):
    startup = get_object_or_404(Startup, slug__iexact=slug)
    return render(request,
                  'organizer/startup_detail.html',
                  {'startup': startup})

startup/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import redirect


def redirect_root(request):
    return redirect('blog_post_list')

blog/templates/blog/base_blog.html
{% extends parent_template|default:"base.html" %}

blog/templates/blog/post_detail.html
{% extends parent_template|default:"blog/base_blog.html" %}


{% block content %}

    <article>
        <header>
            <h2>{{ post.title|title }}</h2>
            <p>Written on:
                <time datetime="{{ post.pub_date|date:"Y-m-d" }}">
                    {{ post.pub_date|date:"l, F j, Y" }}
                </time>
            </p>
        </header>

        {{ post.text|linebreaks }}

        {% if post.startups.all or post.tags.all %}
        <footer>
            {% if post.startups.all %}
                <section>
                <h3>Startup{{ post.startups.count|pluralize }}</h3>
                <ul>
                    {% for startup in post.startups.all %}
                        <li><a href="#">{{ startup.name }}</a> </li>
                    {% endfor %}
                </ul>
                </section>
            {% endif %}

            {% if post.tags.all  %}
                <section>
                <h3>Tag{{ post.tags.count|pluralize }}</h3>
                <ul>
                    {% for tag in post.tags.all %}
                        <li><a href="#">
                            {{ tag.name|title }}
                        </a> </li>
                    {% endfor %}
                </ul>
                </section>
            {% endif %}
        </footer>

        {% endif %}
    </article>

{% endblock %}

blog/templates/blog/post_list.html
{% extends parent_template|default:"blog/base_blog.html" %}


{% block content %}
{% for post in post_list %}
    <article>
        <header>
            <h2><a href="{{ post.get_absolute_url }}">{{ post.title|title }}</a> </h2>
            <p>Written on:
                <time datetime="{{ post.pub_date|date:"Y-m-d" }}">
                    {{ post.pub_date|date:"l, F j, Y" }}
                </time>
            </p>
        </header>
        <p> {{  post.text|truncatechars:20 }}</p>
        <a href="{{ post.get_absolute_url }}">Read more&hellip;</a>
    </article>
    {% empty %}
    <p><em>No Blog Posts Available.</em></p>
{% endfor %}
{% endblock %}

organizer/templates/organizer/base_organizer.html
{% extends parent_template|default:"base.html" %}

organizer/templates/organizer/startup_detail.html
<article>

    <h2> {{ startup.name }}</h2>
    <dl>
        <dt>Date Founded</dt>
            <dd> {{ startup.founded_date|date:"F jS, Y" }}</dd>
        <dt>Website</dt>
            <dd>{{ startup.website|urlize}}</dd>
        <dt>Contact</dt>
            <dd> {{ startup.contact }}</dd>
        <dt>Tag{{ startup.tags.count|pluralize }}</dt>
        {% for tag in startup.tags.all %}
            <dd><a href="#">{{ tag.name|title }}</a> </dd>
        {% endfor  %}
    </dl>

    {{ startup.description|linebreaks }}
    {% if startup.newslink_set.all %}
        <section>
            <h3>Recent News</h3>
            <ul>
                {% for newslink in startup.newslink_set.all %}
                    <li>
                    {{ newslink.title|urlize }}
                    </li>
                {% endfor %}
            </ul>
        </section>
    {% endif %}

    {% if startup.blog_posts.all %}
        <section>
            <h3>Blog Post{{ startup.blog_posts.count|pluralize }}</h3>
            <ul>
                {% for post in startup.blog_posts.all %}
                    <li>
                    {{ post.title|urlize }}
                    </li>
                {% endfor %}
            </ul>
        </section>
    {% endif %}

</article>

organizer/templates/organizer/startup_list.html
{% extends parent_template|default:"organizer/base_organizer.html" %}


{% block content %}
<h2>Startup List</h2>
<ul>
    {% for startup in startup_list %}
        <li>
            <a href="{{ startup.get_absolute_url }}">{{ startup.name|urlize }}</a>
        </li>

        {% empty %}
        <li><em>No Startups Available.</em></li>
    {% endfor %}
</ul>
{% endblock %}

organizer/templates/organizer/tag_detail.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
    {{ block.super }} - {{ tag.name|title }}
{% endblock %}


{% block content %}
{% if tag.startup_set.all %}

    <h2> {{ tag.name|title }}</h2>
    <section>
        <h3> Startup{{ tag.startup_set.count|pluralize   }}</h3>
        <ul>
            <!-- List of startups related to tag -->
            {% for startup in tag.startup_set.all %}
                <li>
                    <a href="{{ startup.get_absolute_url }}"> {{ startup.name }} </a>
                </li>
            {% endfor %}
        </ul>
    </section>

    <p>Tag is associated with {{ tag.startup_set.count }} startup{{ tag.startup_set.count|pluralize }}.</p>
{% endif %}

{% if tag.blog_posts.all %}
    <section>
        <h3> Blog Post{{ tag.startup_set.count|pluralize  }}</h3>
        <ul>
            <!-- List of posts related to tag -->
            {% for post in tag.blog_posts.all %}
                <li><a href="{{ post.get_absolute_url }}">
                    {{ post.title|title }}
                </a> </li>
            {% endfor %}
        </ul>
    </section>
{% endif %}

{% if not tag.startup_set.all and not tag.blog_posts.all %}
    <p>This tag is not related to any content. </p>
{% endif %}

{% endblock %}

organizer/templates/organizer/tag_form.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
    {{ block.super }} - Create Tag
{% endblock %}

{% block content %}

{#    {% for field in form %}#}
{#        {{ field.errors }}#}
{#        <p>#}
{#        {{ field.label_tag }}#}
{#        {{ field }}#}
{#        {% if field.help_text %}#}
{#            <span class="helptext">#}
{#            {{ field.help_text }}#}
{#            </span>#}
{#        {% endif %}#}
{#        </p>#}
{#    {% endfor %}#}


    <form action="{% url 'organizer_tag_create' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Create Tag</button>
    </form>
{% endblock %}

organizer/templates/organizer/tag_form_old.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
    {{ block.super }} - Create Tag
{% endblock %}

{% block content %}
<form action="{% url 'organizer_tag_create' %}" method="post">
 {% csrf_token %}
<p>
{#    <label for="{{ form.name.id_for_label }}">{{ form.name.label }}</label>#}
{#    {% if form.name.value %}#}
{#        <input id="id_name" maxlength="31" name="name" type="text" value="{{ form.name.value }}"/>#}
{#    {% else %}#}
{#        <input id="id_name" maxlength="31" name="name" type="text"/>#}
{#    {% endif %}#}
        {{ form.name.label_tag }}
        {{ form.name }}
        {{ form.name.errors }}
{#    {% if form.name.errors %}#}
{#        <ul class="custom_error_list">#}
{#            {% for error in form.name.errors %}#}
{#                <li><em>{{ error }}</em></li>#}
{#            {% endfor %}#}
{#        </ul>#}
{#    {% endif %}#}
</p>

<p>
{#    <label for="id_slug">Slug:</label>#}
{#    {% if form.slug.value %}#}
{#        <input id="id_name" maxlength="31" name="slug" type="text" value="{{ form.slug.value }}"/>#}
{#    {% else %}#}
{#        <input id="id_name" maxlength="31" name="slug" type="text"/>#}
{#    {% endif %}#}
{#    <label for="{{ form.slug.id_for_label }}">{{ form.slug.label }}</label>#}
    {{ form.slug.label_tag }}
    {{ form.slug }}

    <span class="helptext">{{ form.slug.help_text }}</span>

{#    {% if form.slug.errors %}#}
{#        <ul class="custom_error_list">#}
{#            {% for error in form.slug.errors %}#}
{#                <li><em>{{ error }}</em></li>#}
{#            {% endfor %}#}
{#        </ul>#}
{#    {% endif %}#}
    {{ form.slug.errors }}
</p>

<button type="submit">Create Tag</button>
</form>
{% endblock %}

organizer/templates/organizer/tag_list.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
    {{ block.super }} - Tag List
{% endblock %}

{% block content %}
<h2>Tag List</h2>
    <div>
        <a href="{% url 'organizer_tag_create' %}">Create New Tag</a>
    </div>
    <ul>
        {% for tag in tag_list %}
            <li>
            <a href="{{ tag.get_absolute_url }}"> {{ tag.name|title }}</a>
            </li>
        {% empty %}
        <li><em> There are currently no Tags available.</em></li>
    {% endfor %}
     </ul>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>
        {% block title %}
            Startup Organizer
        {% endblock %}
    </title>
</head>

<body>
<div>
    <header>Startup Organizer</header>
    <main>
        <nav>
            <ul>
                <li><a href="{% url 'blog_post_list' %}"> Blog</a></li>
            </ul>
            <ul>
                <li><a href="{% url 'organizer_startup_list' %}"> Startups</a></li>
            </ul>
            <ul>
                <li><a href="{% url 'organizer_tag_list' %}"> Tags</a></li>
            </ul>
        </nav>
        {% block content %}
        This is default content!
        {% endblock %}
    </main>
</div>

<footer>
    <p> &copy; 2018</p>
</footer>
</body>
</html>